# For testing:
NUM_CUSTOMERS = 50
CONTROL_GROUP_PERCENTAGE = 0.5
NUM_PRODUCTS = 5
NUM_PHYSICAL_STORES = 5
NUM_CAMPAIGNS = 10
AUDIENCE_PERCENTAGE = 1
# Actual Numbers:
# NUM_CUSTOMERS = 50000
# CONTROL_GROUP_PERCENTAGE = 0.1
# NUM_PRODUCTS = 10000
# NUM_PHYSICAL_STORES = 50
# NUM_CAMPAIGNS = 50
# AUDIENCE_PERCENTAGE = 0.1
